CREATE TABLE "github_pull_requests" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"number" integer NOT NULL,
	"title" varchar(512) NOT NULL,
	"body" text,
	"state" varchar(50) NOT NULL,
	"draft" boolean DEFAULT false,
	"locked" boolean DEFAULT false,
	"html_url" varchar(512) NOT NULL,
	"diff_url" varchar(512),
	"patch_url" varchar(512),
	"issue_url" varchar(512),
	"merged" boolean DEFAULT false,
	"merged_at" timestamp,
	"closed_at" timestamp,
	"merge_commit_sha" varchar(255),
	"commits" integer DEFAULT 0,
	"additions" integer DEFAULT 0,
	"deletions" integer DEFAULT 0,
	"changed_files" integer DEFAULT 0,
	"comments" integer DEFAULT 0,
	"review_comments" integer DEFAULT 0,
	"head_ref" varchar(255),
	"head_sha" varchar(255),
	"base_ref" varchar(255),
	"base_sha" varchar(255),
	"repository_id" varchar(255),
	"mergeable" boolean,
	"maintainer_can_modify" boolean DEFAULT false,
	"user_data" jsonb,
	"assignee_data" jsonb,
	"assignees_data" jsonb,
	"merged_by_data" jsonb,
	"labels" jsonb,
	"milestone_data" jsonb,
	"requested_reviewers_data" jsonb,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE "oauth_tokens" ALTER COLUMN "id" SET DEFAULT 'e8f87aba-3b93-459f-97a3-280798226a2f';