version: "3.9"
services:
  ait_postgres:
    image: postgres:latest
    container_name: ait_postgres_ci
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ait
    ports:
      - "5432:5432"
    volumes:
      - pgdata_ci:/var/lib/postgresql/data
    networks:
      - app-network

  ait_qdrant:
    image: qdrant/qdrant:latest
    container_name: ait_qdrant_ci
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage_ci:/qdrant/storage
    networks:
      - app-network

volumes:
  pgdata_ci:
  qdrant_storage_ci:

networks:
  app-network:
    driver: bridge
