packages:
  - packages/*
  - packages/infrastructure/*
  - '!packages/infrastructure/scheduler'
  - packages/core/*
  - packages/connectors/*
  - packages/transformers/*
  - packages/gateway/*
  - packages/uit/*
  - packages/rocks/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'

onlyBuiltDependencies:
  - protobufjs
