name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  setup-dependencies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the Project
        run: pnpm build

  package-tests:
    needs: setup-dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [20, 22]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint the Project
        run: pnpm lint

      - name: Build the Project
        run: pnpm build

      - name: Start Services
        run: docker compose -f docker-compose.ci.yml up -d

      - name: Wait for PostgreSQL to be Healthy
        run: |
          docker compose -f docker-compose.ci.yml exec -T ait_postgres_ci sh -c "until pg_isready -U root; do echo 'Waiting for PostgreSQL to be healthy...'; sleep 5; done"

      - name: Wait for Qdrant to be Healthy
        run: |
          # check status 200
          until curl -f http://localhost:6333; do
            echo "Waiting for Qdrant to be healthy..."
            sleep 5
          done
          echo "Qdrant is healthy."

      - name: Run Tests
        run: pnpm test

      - name: Tear Down Services
        if: always()
        run: docker compose -f docker-compose.ci.yml down
